/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUDbdl;

import Login.ConnectDatabaseLoginBDL;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alghi
 */
public class DialogDetailAset extends javax.swing.JDialog {

    private String kodeAset;
    private DefaultTableModel modelRiwayat;

    /**
     * Creates new form DialogDetailAset
     */
    public DialogDetailAset(java.awt.Frame parent, boolean modal, Object ignoredRepo, String kodeAset) {
        super(parent, modal);
        initComponents();
        this.kodeAset = kodeAset;

        // 1. Setup Form
        setLocationRelativeTo(null);
        setTitle("Detail Aset & Riwayat");

        // 2. Setup Table Model
        modelRiwayat = new DefaultTableModel(new String[]{
            "ID Maint", "Tgl Mulai", "Tgl Selesai", "Masalah", "Biaya", "Teknisi"
        }, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblRiwayat.setModel(modelRiwayat);

        // 3. Load Data
        loadInfoAset();
        loadRiwayatMaintenance();
    }

    private void loadInfoAset() {
        try {
            Connection conn = ConnectDatabaseLoginBDL.getConnection();

            // Join to get readable names instead of IDs
            String sql = "SELECT a.*, k.nama_kategori, l.nama_lokasi, p.nama_pegawai "
             + "FROM aset a "
             + "LEFT JOIN kategori k ON a.id_kategori = k.id_kategori "
             + "LEFT JOIN lokasi l ON a.id_lokasi = l.id_lokasi "
             + "LEFT JOIN pegawai p ON a.id_pegawai = p.id_pegawai "
             + "WHERE a.kode_aset_unik = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kodeAset);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Format Currency
                double nilai = rs.getDouble("nilai_buku");
                java.text.NumberFormat cur = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));

                // Set Text to Labels (Make sure these Variable Names match your GUI!)
                lblKode.setText(rs.getString("kode_aset_unik"));
                lblNama.setText(rs.getString("nama_aset"));
                lblKategori.setText(rs.getString("nama_kategori"));
                lblLokasi.setText(rs.getString("nama_lokasi"));
                lblPJ.setText(rs.getString("nama_pegawai"));
                lblNilai.setText(cur.format(nilai));
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Error Info: " + e);
        }
    }

    private void loadRiwayatMaintenance() {
        try {
            Connection conn = ConnectDatabaseLoginBDL.getConnection();

            // Get Maintenance history + Aggregate Technician Names
            // We use string_agg to combine multiple technicians into one string
            String sql = "SELECT m.id_pemeliharaan, m.tanggal_mulai, m.tanggal_selesai, m.deskripsi_masalah, m.total_biaya, "
             + "(SELECT string_agg(p.nama_pegawai, ', ') FROM pemeliharaan_pegawai pp "
             + " JOIN pegawai p ON pp.id_pegawai = p.id_pegawai WHERE pp.id_pemeliharaan = m.id_pemeliharaan) as list_teknisi "
             + "FROM pemeliharaan m "
             + "WHERE m.kode_aset_unik = ? ORDER BY m.tanggal_mulai DESC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, kodeAset);
            ResultSet rs = ps.executeQuery();

            modelRiwayat.setRowCount(0);
            while (rs.next()) {
                // Handle Null Date
                Date tglSelesai = rs.getDate("tanggal_selesai");
                String selesaiStr = (tglSelesai == null) ? "Sedang Berjalan" : tglSelesai.toString();

                modelRiwayat.addRow(new Object[]{
                    rs.getString("id_pemeliharaan"),
                    rs.getString("tanggal_mulai"),
                    selesaiStr,
                    rs.getString("deskripsi_masalah"),
                    rs.getDouble("total_biaya"),
                    rs.getString("list_teknisi") // e.g. "Budi, Siti"
                });
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Error Riwayat: " + e);
        }
    }

    // ... (rest of initComponents() and main method)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneHistory = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        pnlInfoAset = new javax.swing.JPanel();
        lblKodeAset = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblNamaAset = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKategoriTitle = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblTanggalPerolehan = new javax.swing.JLabel();
        lblIsianTanggalPeolehan = new javax.swing.JLabel();
        lblHargaAwal = new javax.swing.JLabel();
        lblNilai = new javax.swing.JLabel();
        lblLokasiSaatIni = new javax.swing.JLabel();
        lblLokasi = new javax.swing.JLabel();
        lblPJTitle = new javax.swing.JLabel();
        lblPJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Aset & Riwayat Nilai");

        jScrollPaneHistory.setToolTipText("Histori Perubahan Nilai (Penyusutan)");

        tblRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanngal_Hitung", "Metode", "Turun_Nilai", "Nilai_Sisa"
            }
        ));
        jScrollPaneHistory.setViewportView(tblRiwayat);

        getContentPane().add(jScrollPaneHistory, java.awt.BorderLayout.CENTER);

        pnlInfoAset.setToolTipText("Informasi Aset");
        pnlInfoAset.setLayout(new java.awt.GridLayout(8, 2, 5, 5));

        lblKodeAset.setText("Kode Aset:");
        pnlInfoAset.add(lblKodeAset);
        pnlInfoAset.add(lblKode);

        lblNamaAset.setText("Nama Aset:");
        pnlInfoAset.add(lblNamaAset);
        pnlInfoAset.add(lblNama);

        lblKategoriTitle.setText("Kategori:");
        pnlInfoAset.add(lblKategoriTitle);
        pnlInfoAset.add(lblKategori);

        lblTanggalPerolehan.setText("Tanggal Perolehan:");
        pnlInfoAset.add(lblTanggalPerolehan);
        pnlInfoAset.add(lblIsianTanggalPeolehan);

        lblHargaAwal.setText("Harga Awal:");
        pnlInfoAset.add(lblHargaAwal);
        pnlInfoAset.add(lblNilai);

        lblLokasiSaatIni.setText("Lokasi Saat Ini:");
        pnlInfoAset.add(lblLokasiSaatIni);
        pnlInfoAset.add(lblLokasi);

        lblPJTitle.setText("Penanggung Jawab");
        pnlInfoAset.add(lblPJTitle);
        pnlInfoAset.add(lblPJ);

        getContentPane().add(pnlInfoAset, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneHistory;
    private javax.swing.JLabel lblHargaAwal;
    private javax.swing.JLabel lblIsianTanggalPeolehan;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKategoriTitle;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblKodeAset;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblLokasiSaatIni;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaAset;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JLabel lblPJ;
    private javax.swing.JLabel lblPJTitle;
    private javax.swing.JLabel lblTanggalPerolehan;
    private javax.swing.JPanel pnlInfoAset;
    private javax.swing.JTable tblRiwayat;
    // End of variables declaration//GEN-END:variables
}
