/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CRUDbdl;

import javax.swing.table.DefaultTableModel; // Diperlukan untuk DefaultTableModel
import java.util.List; // Diperlukan untuk List
import javax.swing.JOptionPane;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import Login.ConnectDatabaseLoginBDL;
import java.sql.*;

/**
 *
 * @author afrizal
 */
public class FormStokLogistik extends javax.swing.JPanel {

    /**
     * Creates new form FormStokLogistik
     */
    public FormStokLogistik() {
        initComponents();
        // Muat data saat form dibuka
        muatDataLogistikKeTabel();
    }

    // Helper untuk mendapatkan Kode Aset yang dipilih
    private String getLogistikIdDipilih() {
        int barisDipilih = tblinventaris.getSelectedRow();
        if (barisDipilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih satu baris item logistik dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        // Asumsi ID Inventaris ada di kolom pertama (indeks 0)
        return tblinventaris.getValueAt(barisDipilih, 0).toString();
    }

    // Helper untuk mendapatkan Frame Induk
    private Frame getParentFrame() {
        return (Frame) SwingUtilities.getWindowAncestor(this);
    }

    private void muatDataLogistikKeTabel() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblinventaris.getModel();
        model.setRowCount(0);

        try {
            java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();

            String sql = "SELECT i.id_inventaris, k.nama_kategori, i.nama_barang, "
             + "i.satuan, i.stok_saat_ini, i.stok_minimum "
             + "FROM inventaris_stok i "
             + "LEFT JOIN kategori k ON i.id_kategori = k.id_kategori "
             + "ORDER BY i.nama_barang ASC";

            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_inventaris"),
                    rs.getString("nama_kategori"), // Shows Name "Elektronik" instead of ID
                    rs.getString("nama_barang"),
                    rs.getString("satuan"),
                    rs.getInt("stok_saat_ini"),
                    rs.getInt("stok_minimum")
                });
            }
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal load logistik: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeaderInv = new javax.swing.JPanel();
        lblMonitor = new javax.swing.JLabel();
        pnlTombol = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinventaris = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlHeaderInv.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeaderInv.setForeground(new java.awt.Color(255, 255, 255));
        pnlHeaderInv.setLayout(new java.awt.GridLayout(2, 1));

        lblMonitor.setBackground(new java.awt.Color(255, 255, 255));
        lblMonitor.setForeground(new java.awt.Color(0, 0, 0));
        lblMonitor.setText("<html><b>📦 MONITOR KETERSEDIAAN BARANG LOGISTIK</b> <span style='background-color:#e74c3c; color:white'</html> ");
        lblMonitor.setToolTipText("");
        lblMonitor.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        lblMonitor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblMonitor.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlHeaderInv.add(lblMonitor);

        pnlTombol.setBackground(new java.awt.Color(255, 255, 255));
        pnlTombol.setForeground(new java.awt.Color(255, 255, 255));
        pnlTombol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("🔄 Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pnlTombol.add(btnRefresh);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("✏️ Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlTombol.add(btnEdit);

        pnlHeaderInv.add(pnlTombol);

        add(pnlHeaderInv, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tblinventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Inventaris", "Kategori", "Nama Barang", "Satuan", "Stok Saat Ini", "Stok Minimum"
            }
        ));
        jScrollPane1.setViewportView(tblinventaris);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        muatDataLogistikKeTabel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String idInventaris = getLogistikIdDipilih();
        if (idInventaris == null) {
            return;
        }

        java.awt.Frame parentFrame = getParentFrame();

        // Pass 'null' because the dialog now handles its own connection
        FormDialogEditLogistik formEdit = new FormDialogEditLogistik(parentFrame, true, null, idInventaris);

        formEdit.setLocationRelativeTo(this);
        formEdit.setVisible(true);

        muatDataLogistikKeTabel();

    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMonitor;
    private javax.swing.JPanel pnlHeaderInv;
    private javax.swing.JPanel pnlTombol;
    private javax.swing.JTable tblinventaris;
    // End of variables declaration//GEN-END:variables
}
