/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUDbdl;

/**
 *
 * @author alghi
 */
public class FormDialogEditLogistik extends javax.swing.JDialog {

    private String idInventaris;
    private java.util.HashMap<String, String> mapKategori = new java.util.HashMap<>();

    public FormDialogEditLogistik(java.awt.Frame parent, boolean modal, Object ignoredRepo, String idInventaris) {
        super(parent, modal);
        initComponents();
        this.idInventaris = idInventaris;

        // Setup Form
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        txtIdInventaris.setText(idInventaris);
        txtIdInventaris.setEnabled(false); // ID is read-only

        loadKategori();
        loadData();
    }

    private void loadKategori() {
        try {
            java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();
            java.sql.ResultSet rs = conn.createStatement().executeQuery("SELECT id_kategori, nama_kategori FROM kategori");

            cbxKategori.removeAllItems();
            while (rs.next()) {
                String id = rs.getString("id_kategori");
                String nama = rs.getString("nama_kategori");

                cbxKategori.addItem(nama);
                mapKategori.put(nama, id);
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Error Load Kategori: " + e);
        }
    }

    private void loadData() {
        try {
            java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();
            String sql = "SELECT * FROM inventaris_stok WHERE id_inventaris = ?";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idInventaris);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtNamaBarang.setText(rs.getString("nama_barang"));
                txtSatuan.setText(rs.getString("satuan"));
                txtStok.setText(String.valueOf(rs.getInt("stok_saat_ini")));
                txtStokMin.setText(String.valueOf(rs.getInt("stok_minimum")));

                // Set ComboBox selection
                String currentIdKategori = rs.getString("id_kategori");
                for (String nama : mapKategori.keySet()) {
                    if (mapKategori.get(nama).equals(currentIdKategori)) {
                        cbxKategori.setSelectedItem(nama);
                        break;
                    }
                }
            }
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Load: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pnlAksi = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        pnlInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdInventaris = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxKategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStokMin = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Satuan dan Stok Minimum Logistik");
        setModal(true);
        setResizable(false);

        pnlAksi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        pnlAksi.add(btnBatal);

        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        pnlAksi.add(btnSimpan);

        getContentPane().add(pnlAksi, java.awt.BorderLayout.SOUTH);

        pnlInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInput.setToolTipText("pnlInput");
        pnlInput.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setText("ID Inventaris");
        pnlInput.add(jLabel1);

        txtIdInventaris.setEnabled(false);
        pnlInput.add(txtIdInventaris);

        jLabel2.setText("Nama Barang");
        pnlInput.add(jLabel2);
        pnlInput.add(txtNamaBarang);

        jLabel3.setText("Kategori");
        pnlInput.add(jLabel3);

        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlInput.add(cbxKategori);

        jLabel4.setText("Satuan");
        pnlInput.add(jLabel4);
        pnlInput.add(txtSatuan);

        jLabel5.setText("Stok Saat Ini");
        pnlInput.add(jLabel5);
        pnlInput.add(txtStok);

        jLabel6.setText("Stok Minimum");
        pnlInput.add(jLabel6);
        pnlInput.add(txtStokMin);

        getContentPane().add(pnlInput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();
            String sql = "UPDATE inventaris_stok SET nama_barang=?, id_kategori=?, satuan=?, stok_saat_ini=?, stok_minimum=? WHERE id_inventaris=?";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, txtNamaBarang.getText());
            ps.setString(2, mapKategori.get(cbxKategori.getSelectedItem().toString()));
            ps.setString(3, txtSatuan.getText());
            ps.setInt(4, Integer.parseInt(txtStok.getText()));
            ps.setInt(5, Integer.parseInt(txtStokMin.getText()));
            ps.setString(6, idInventaris);

            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data Logistik Diupdate!");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Update: " + e);
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlAksi;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JTextField txtIdInventaris;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokMin;
    // End of variables declaration//GEN-END:variables
}
