/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CRUDbdl;

import javax.swing.table.DefaultTableModel; // Diperlukan untuk DefaultTableModel
import java.util.List; // Diperlukan untuk List
import javax.swing.JOptionPane;
import java.awt.Frame;
import javax.swing.SwingUtilities;
import Login.ConnectDatabaseLoginBDL;
import java.sql.*;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.util.HashMap;

/**
 *
 * @author afrizal
 */
public class FormStokLogistik extends javax.swing.JPanel {

    /**
     * Creates new form FormStokLogistik
     */
    public FormStokLogistik() {
        initComponents();
        // Muat data saat form dibuka
        muatDataLogistikKeTabel();
    }

    // Helper untuk mendapatkan Kode Aset yang dipilih
    private String getLogistikIdDipilih() {
        int barisDipilih = tblinventaris.getSelectedRow();
        if (barisDipilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih satu baris item logistik dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        // Asumsi ID Inventaris ada di kolom pertama (indeks 0)
        return tblinventaris.getValueAt(barisDipilih, 0).toString();
    }

    // Helper untuk mendapatkan Frame Induk
    private Frame getParentFrame() {
        return (Frame) SwingUtilities.getWindowAncestor(this);
    }

    private void muatDataLogistikKeTabel() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblinventaris.getModel();
        model.setRowCount(0);

        try {
            java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();

            String sql = "SELECT i.id_inventaris, k.nama_kategori, i.nama_barang, "
             + "i.satuan, i.stok_saat_ini, i.stok_minimum "
             + "FROM inventaris_stok i "
             + "LEFT JOIN kategori k ON i.id_kategori = k.id_kategori "
             + "ORDER BY i.nama_barang ASC";

            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_inventaris"),
                    rs.getString("nama_kategori"), // Shows Name "Elektronik" instead of ID
                    rs.getString("nama_barang"),
                    rs.getString("satuan"),
                    rs.getInt("stok_saat_ini"),
                    rs.getInt("stok_minimum")
                });
            }
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal load logistik: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeaderInv = new javax.swing.JPanel();
        lblMonitor = new javax.swing.JLabel();
        pnlTombol = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCetakInventaris = new javax.swing.JButton();
        btnCetakRiwayat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinventaris = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlHeaderInv.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeaderInv.setForeground(new java.awt.Color(255, 255, 255));
        pnlHeaderInv.setLayout(new java.awt.GridLayout(2, 1));

        lblMonitor.setBackground(new java.awt.Color(255, 255, 255));
        lblMonitor.setText("<html><b>📦 MONITOR KETERSEDIAAN BARANG LOGISTIK</b> <span style='background-color:#e74c3c; color:white'</html> ");
        lblMonitor.setToolTipText("");
        lblMonitor.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        lblMonitor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblMonitor.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlHeaderInv.add(lblMonitor);

        pnlTombol.setBackground(new java.awt.Color(255, 255, 255));
        pnlTombol.setForeground(new java.awt.Color(255, 255, 255));
        pnlTombol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnRefresh.setText("🔄 Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pnlTombol.add(btnRefresh);

        btnEdit.setText("✏️ Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlTombol.add(btnEdit);

        btnCetakInventaris.setText("Cetak Laporan Inventaris");
        btnCetakInventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakInventarisActionPerformed(evt);
            }
        });
        pnlTombol.add(btnCetakInventaris);

        btnCetakRiwayat.setText("Cetak Riwayat");
        btnCetakRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakRiwayatActionPerformed(evt);
            }
        });
        pnlTombol.add(btnCetakRiwayat);

        pnlHeaderInv.add(pnlTombol);

        add(pnlHeaderInv, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblinventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Inventaris", "Kategori", "Nama Barang", "Satuan", "Stok Saat Ini", "Stok Minimum"
            }
        ));
        jScrollPane1.setViewportView(tblinventaris);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        muatDataLogistikKeTabel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String idInventaris = getLogistikIdDipilih();
        if (idInventaris == null) {
            return;
        }

        java.awt.Frame parentFrame = getParentFrame();

        // Pass 'null' because the dialog now handles its own connection
        FormDialogEditLogistik formEdit = new FormDialogEditLogistik(parentFrame, true, null, idInventaris);

        formEdit.setLocationRelativeTo(this);
        formEdit.setVisible(true);

        muatDataLogistikKeTabel();

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCetakInventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakInventarisActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();

            // 1. Load & Compile the Report
            // Make sure the filename matches what you created in Studio
            String reportPath = "src/LaporanStokLogistik.jrxml";
            File reportFile = new File(reportPath);

            if (!reportFile.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this, "File report tidak ditemukan di: " + reportPath);
                return;
            }

            JasperDesign design = JRXmlLoader.load(reportFile);
            JasperReport report = JasperCompileManager.compileReport(design);

            // 2. Parameters (Empty because we don't need date filters for current stock)
            HashMap<String, Object> parameters = new HashMap<>();

            // Optional: You can pass the "Printed By" name if you want
            // parameters.put("user", "Admin");
            // 3. Print
            JasperPrint print = JasperFillManager.fillReport(report, parameters, conn);
            JasperViewer.viewReport(print, false); // false = Don't close app on exit

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Cetak: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCetakInventarisActionPerformed

    private void btnCetakRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakRiwayatActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField txtMulai = new javax.swing.JTextField(10);
        javax.swing.JTextField txtSelesai = new javax.swing.JTextField(10);

        String currentYear = java.time.Year.now().toString();
        txtMulai.setText(currentYear + "-01-01");
        txtSelesai.setText(currentYear + "-12-31");

        Object[] message = {
            "Lihat Riwayat Penggunaan Barang:",
            "Dari Tanggal (YYYY-MM-DD):", txtMulai,
            "Sampai Tanggal (YYYY-MM-DD):", txtSelesai
        };

        int option = javax.swing.JOptionPane.showConfirmDialog(null, message, "Filter Riwayat Logistik", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (option == javax.swing.JOptionPane.OK_OPTION) {
            try {
                // 2. Parse Dates
                java.sql.Date tglMulai = java.sql.Date.valueOf(txtMulai.getText());
                java.sql.Date tglSelesai = java.sql.Date.valueOf(txtSelesai.getText());

                java.sql.Connection conn = Login.ConnectDatabaseLoginBDL.getConnection();

                // 3. Load Report
                String reportPath = "src/LaporanPenggunaan.jrxml";
                java.io.File reportFile = new java.io.File(reportPath);

                if (!reportFile.exists()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "File report tidak ditemukan!");
                    return;
                }

                // 4. Compile
                net.sf.jasperreports.engine.design.JasperDesign design = net.sf.jasperreports.engine.xml.JRXmlLoader.load(reportFile);
                net.sf.jasperreports.engine.JasperReport report = net.sf.jasperreports.engine.JasperCompileManager.compileReport(design);

                // 5. Pass Parameters
                java.util.HashMap<String, Object> parameters = new java.util.HashMap<>();
                parameters.put("StartDate", tglMulai);
                parameters.put("EndDate", tglSelesai);

                // 6. Print
                net.sf.jasperreports.engine.JasperPrint print
                 = net.sf.jasperreports.engine.JasperFillManager.fillReport(report, parameters, conn);

                net.sf.jasperreports.view.JasperViewer.viewReport(print, false);

            } catch (IllegalArgumentException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Format Tanggal Salah! Gunakan YYYY-MM-DD");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal Cetak: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCetakRiwayatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakInventaris;
    private javax.swing.JButton btnCetakRiwayat;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMonitor;
    private javax.swing.JPanel pnlHeaderInv;
    private javax.swing.JPanel pnlTombol;
    private javax.swing.JTable tblinventaris;
    // End of variables declaration//GEN-END:variables
}
