/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LEGION
 */
public class DaftarBDL extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DaftarBDL.class.getName());

    /**
     * Creates new form DaftarBDL
     */
    public DaftarBDL() {
        initComponents();
        btnKonfirmasi.addActionListener(e -> daftarAkun());
    }

    // Tambahkan method daftarAkun()
    private void daftarAkun() {
        String username = txtUsername.getText().trim();
        String password = new String(PasswordField.getPassword());
        String confirmPassword = new String(ConfirmPasswordField.getPassword());
        String question = txtPertanyaan.getText().trim();
        String answer = txtJawaban.getText().trim();

        // Validasi input
        if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()
                || question.isEmpty() || answer.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Password dan konfirmasi password tidak cocok!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmtCheck = null;
        PreparedStatement pstmtInsertLogin = null;
        PreparedStatement pstmtInsertSecurity = null;
        ResultSet rs = null;

        try {
            conn = ConnectDatabaseLoginBDL.getConnection();

            // Cek apakah username sudah ada
            String checkSQL = "SELECT username FROM login WHERE username = ?";
            pstmtCheck = conn.prepareStatement(checkSQL);
            pstmtCheck.setString(1, username);
            rs = pstmtCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Username sudah digunakan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Mulai transaksi
            conn.setAutoCommit(false);

            // Insert ke tabel login
            String insertLoginSQL = "INSERT INTO login (username, passwordnya) VALUES (?, ?)";
            pstmtInsertLogin = conn.prepareStatement(insertLoginSQL);
            pstmtInsertLogin.setString(1, username);
            pstmtInsertLogin.setString(2, password); // Dalam aplikasi nyata, password harus di-hash
            pstmtInsertLogin.executeUpdate();

            // Insert ke tabel security_question
            String insertSecuritySQL = "INSERT INTO security_question (username, question, answer_hash) VALUES (?, ?, ?)";
            pstmtInsertSecurity = conn.prepareStatement(insertSecuritySQL);
            pstmtInsertSecurity.setString(1, username);
            pstmtInsertSecurity.setString(2, question);
            pstmtInsertSecurity.setString(3, answer); // Dalam aplikasi nyata, jawaban harus di-hash
            pstmtInsertSecurity.executeUpdate();

            // Commit transaksi
            conn.commit();

            JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Kembali ke login
            this.dispose();
            new LoginBDL().setVisible(true);

        } catch (SQLException ex) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            ConnectDatabaseLoginBDL.closeConnection(conn, pstmtInsertSecurity, rs);
            ConnectDatabaseLoginBDL.closeConnection(null, pstmtCheck, null);
            ConnectDatabaseLoginBDL.closeConnection(null, pstmtInsertLogin, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDaftarAkun = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        lblPertanyaanKeamanan = new javax.swing.JLabel();
        lblJawaban = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        txtPertanyaan = new javax.swing.JTextField();
        txtJawaban = new javax.swing.JTextField();
        btnKonfirmasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDaftarAkun.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDaftarAkun.setText("Daftar Akun");

        lblUsername.setText("Masukkan Username");

        lblPassword.setText("Masukkan Password");

        lblConfirmPassword.setText("Konfirmasi Password");

        lblPertanyaanKeamanan.setText("Pertanyaan Keamanan");

        lblJawaban.setText("Jawaban");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });

        txtPertanyaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPertanyaanActionPerformed(evt);
            }
        });

        txtJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJawabanActionPerformed(evt);
            }
        });

        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword)
                    .addComponent(lblConfirmPassword)
                    .addComponent(lblPertanyaanKeamanan)
                    .addComponent(lblJawaban))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(PasswordField)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtPertanyaan)
                    .addComponent(txtJawaban))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 130, Short.MAX_VALUE)
                .addComponent(lblDaftarAkun)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnKonfirmasi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDaftarAkun)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPertanyaanKeamanan)
                    .addComponent(txtPertanyaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJawaban)
                    .addComponent(txtJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnKonfirmasi)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void txtPertanyaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPertanyaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPertanyaanActionPerformed

    private void txtJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJawabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJawabanActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblDaftarAkun;
    private javax.swing.JLabel lblJawaban;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPertanyaanKeamanan;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtJawaban;
    private javax.swing.JTextField txtPertanyaan;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
