/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author LEGION
 */
public class LupaPasswordBDL extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LupaPasswordBDL.class.getName());

    /**
     * Creates new form LupaPasswordBDL
     */
    private String username;

    public LupaPasswordBDL(String username) {
        initComponents();
        this.username = username;

        btnEnter.addActionListener(e -> ubahPassword());

        // Tambahkan WindowListener untuk handle close
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                new LoginBDL().setVisible(true);
            }
        });
    }

    private void ubahPassword() {
        String passwordBaru = txtPasswordbaru.getText().trim();
        String konfirmasi = txtKonfirmasiPasswordBaru.getText().trim();

        if (passwordBaru.isEmpty() || konfirmasi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!passwordBaru.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(null, "Password baru dan konfirmasi tidak cocok!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmt = null;

        try {
            conn = ConnectDatabaseLoginBDL.getConnection();

            // PERUBAHAN: Update password di tabel pegawai
            String sql = "UPDATE pegawai SET password = ? WHERE username = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, passwordBaru);
            pstmt.setString(2, username);

            int rowsUpdated = pstmt.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Password berhasil diubah!", "Success", JOptionPane.INFORMATION_MESSAGE);
                new LoginBDL().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal mengubah password. Username tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            ConnectDatabaseLoginBDL.closeConnection(conn, pstmt, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUbahPassword = new javax.swing.JLabel();
        lblMasukkanPasswordBaru = new javax.swing.JLabel();
        lblKonfirmasiPasswordbaru = new javax.swing.JLabel();
        txtPasswordbaru = new javax.swing.JTextField();
        txtKonfirmasiPasswordBaru = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUbahPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUbahPassword.setText("Ubah Password");

        lblMasukkanPasswordBaru.setText("Masukkan Password baru");

        lblKonfirmasiPasswordbaru.setText("Konfirmasi Password baru");

        txtPasswordbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordbaruActionPerformed(evt);
            }
        });

        txtKonfirmasiPasswordBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKonfirmasiPasswordBaruActionPerformed(evt);
            }
        });

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUbahPassword)
                    .addComponent(lblKonfirmasiPasswordbaru)
                    .addComponent(lblMasukkanPasswordBaru)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtKonfirmasiPasswordBaru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(txtPasswordbaru, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnter)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblUbahPassword)
                .addGap(18, 18, 18)
                .addComponent(lblMasukkanPasswordBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordbaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblKonfirmasiPasswordbaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKonfirmasiPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnEnter)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordbaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordbaruActionPerformed

    private void txtKonfirmasiPasswordBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKonfirmasiPasswordBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKonfirmasiPasswordBaruActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel lblKonfirmasiPasswordbaru;
    private javax.swing.JLabel lblMasukkanPasswordBaru;
    private javax.swing.JLabel lblUbahPassword;
    private javax.swing.JTextField txtKonfirmasiPasswordBaru;
    private javax.swing.JTextField txtPasswordbaru;
    // End of variables declaration//GEN-END:variables
}
