/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author LEGION
 */
public class LupaUsernameBDL extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LupaUsernameBDL.class.getName());

    /**
     * Creates new form LupaUsernameBDL
     */
    public LupaUsernameBDL() {
        initComponents();

        btnEnter.addActionListener(e -> cariUsername());

        // Tambahkan WindowListener
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                new LoginBDL().setVisible(true);
            }
        });
    }

// Tambahkan method cariUsername()
    private void cariUsername() {
        String kataKunci = txtKataKunciUsername.getText().trim();
        String password = new String(PasswordField.getPassword());

        if (kataKunci.length() < 3) {
            JOptionPane.showMessageDialog(this, "Masukkan minimal 3 karakter untuk pencarian!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = ConnectDatabaseLoginBDL.getConnection();

            // Cari username yang mengandung kata kunci (case-insensitive)
            String sql = "SELECT username FROM login WHERE LOWER(username) LIKE LOWER(?) AND passwordnya = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, "%" + kataKunci + "%");
            pstmt.setString(2, password);
            rs = pstmt.executeQuery();

            List<String> usernames = new ArrayList<>();
            while (rs.next()) {
                usernames.add(rs.getString("username"));
            }

            if (usernames.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password salah atau tidak ada username yang cocok!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (usernames.size() == 1) {
                // Jika hanya satu username yang ditemukan, langsung buka form ubah username
                new UbahUsernameBDL(usernames.get(0)).setVisible(true);
                dispose();
            } else {
                // Jika banyak username, tampilkan pilihan
                String message = "Ditemukan " + usernames.size() + " username:\n";
                for (int i = 0; i < usernames.size(); i++) {
                    message += (i + 1) + ". " + usernames.get(i) + "\n";
                }
                message += "\nPilih nomor username yang ingin diubah:";

                String input = JOptionPane.showInputDialog(this, message, "Pilih Username", JOptionPane.QUESTION_MESSAGE);

                if (input != null) {
                    try {
                        int index = Integer.parseInt(input.trim()) - 1;
                        if (index >= 0 && index < usernames.size()) {
                            new UbahUsernameBDL(usernames.get(index)).setVisible(true);
                            dispose();
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Input tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            ConnectDatabaseLoginBDL.closeConnection(conn, pstmt, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKataKunciUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Lupa Username");

        jLabel2.setText("Masukkan kata kunci username");

        txtKataKunciUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKataKunciUsernameActionPerformed(evt);
            }
        });

        jLabel3.setText("Konfirmasi Password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtKataKunciUsername)
                            .addComponent(jLabel3)
                            .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnter)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKataKunciUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnter)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKataKunciUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataKunciUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKataKunciUsernameActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKataKunciUsername;
    // End of variables declaration//GEN-END:variables
}
