/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author LEGION
 */
public class UbahUsernameBDL extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UbahUsernameBDL.class.getName());

    /**
     * Creates new form UbahUsernameBDL
     */
    private String usernameLama;

    public UbahUsernameBDL(String usernameLama) {
        initComponents();
        this.usernameLama = usernameLama;

        btnEnter.addActionListener(e -> ubahUsername());
    }

// Tambahkan method ubahUsername()
    private void ubahUsername() {
        String usernameBaru = txtUsernameBaru.getText().trim();
        String password = new String(PasswordField.getPassword());

        if (usernameBaru.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username baru tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmtCheck = null;
        PreparedStatement pstmtUpdateLogin = null;
        PreparedStatement pstmtUpdateSecurity = null;
        ResultSet rs = null;

        try {
            conn = ConnectDatabaseLoginBDL.getConnection();

            // Cek apakah username baru sudah ada
            String checkSQL = "SELECT username FROM login WHERE username = ?";
            pstmtCheck = conn.prepareStatement(checkSQL);
            pstmtCheck.setString(1, usernameBaru);
            rs = pstmtCheck.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Username baru sudah digunakan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verifikasi password
            String verifySQL = "SELECT username FROM login WHERE username = ? AND passwordnya = ?";
            pstmtCheck = conn.prepareStatement(verifySQL);
            pstmtCheck.setString(1, usernameLama);
            pstmtCheck.setString(2, password);
            rs = pstmtCheck.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Mulai transaksi
            conn.setAutoCommit(false);

            // Update tabel login
            String updateLoginSQL = "UPDATE login SET username = ? WHERE username = ?";
            pstmtUpdateLogin = conn.prepareStatement(updateLoginSQL);
            pstmtUpdateLogin.setString(1, usernameBaru);
            pstmtUpdateLogin.setString(2, usernameLama);
            pstmtUpdateLogin.executeUpdate();

            // Update tabel security_question
            String updateSecuritySQL = "UPDATE security_question SET username = ? WHERE username = ?";
            pstmtUpdateSecurity = conn.prepareStatement(updateSecuritySQL);
            pstmtUpdateSecurity.setString(1, usernameBaru);
            pstmtUpdateSecurity.setString(2, usernameLama);
            pstmtUpdateSecurity.executeUpdate();

            // Commit transaksi
            conn.commit();

            JOptionPane.showMessageDialog(this, "Username berhasil diubah!", "Success", JOptionPane.INFORMATION_MESSAGE);

            new LoginBDL().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            ConnectDatabaseLoginBDL.closeConnection(conn, pstmtUpdateSecurity, rs);
            ConnectDatabaseLoginBDL.closeConnection(null, pstmtCheck, null);
            ConnectDatabaseLoginBDL.closeConnection(null, pstmtUpdateLogin, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUbahUsername = new javax.swing.JLabel();
        lblUsernameBaru = new javax.swing.JLabel();
        lblKonfirmasiPassword = new javax.swing.JLabel();
        txtUsernameBaru = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUbahUsername.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUbahUsername.setText("Ubah Username");

        lblUsernameBaru.setText("Masukkan Username baru");

        lblKonfirmasiPassword.setText("Konfirmasi Password");

        btnEnter.setText("Enter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUbahUsername)
                    .addComponent(lblKonfirmasiPassword)
                    .addComponent(lblUsernameBaru)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtUsernameBaru, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnter)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUbahUsername)
                .addGap(18, 18, 18)
                .addComponent(lblUsernameBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblKonfirmasiPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnter)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel lblKonfirmasiPassword;
    private javax.swing.JLabel lblUbahUsername;
    private javax.swing.JLabel lblUsernameBaru;
    private javax.swing.JTextField txtUsernameBaru;
    // End of variables declaration//GEN-END:variables
}
