/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUDbdl;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.Frame;
import javax.swing.JOptionPane;
import java.util.Optional;
/**
 *
 * @author alghi
 */
public class DialogDetailAset extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetailAset.class.getName());
private Object jpaDataAccessObject; 
    private String kodeAset;
    /**
     * Creates new form DialogDetailAset
     */
   public DialogDetailAset(java.awt.Frame parent, boolean modal, Object jpaContext, String kodeAset) {
        super(parent, modal);
        this.jpaDataAccessObject = jpaContext; // Simpan EntityManager / AsetRepository
        this.kodeAset = kodeAset; 
        
        // Perbaiki urutan inisialisasi
        initComponents();
        aturTampilanVisual();
        muatDataAset(); 
        
        // Hapus: pack() dipanggil oleh Form pemanggil (FormAset) setelah ini.
    }
    
public DialogDetailAset(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null); 
    }

private void aturTampilanVisual() {
    setTitle("Detail Aset & Riwayat Nilai - " + (kodeAset != null ? kodeAset : "")); 
    
    pnlInfoAset.setBorder(new TitledBorder("Informasi Aset"));
    jScrollPaneHistory.setBorder(new TitledBorder("Histori Perubahan Nilai (Penyusutan)"));
    
    // PERBAIKI NAMA KOLOM AGAR LEBIH JELAS
    tblHistory.setModel(new javax.swing.table.DefaultTableModel(
          new Object [][] {},
          new String [] {"Tanggal Hitung", "Metode", "Nilai Turun", "Nilai Sisa"} 
    ));
}
private void muatDataAset() {
  if (this.kodeAset == null || jpaDataAccessObject == null) {
        System.err.println("Kode Aset atau Repository belum disetel.");
        return;
    }

    try {
        AsetRepository repo = (AsetRepository) this.jpaDataAccessObject;
        Optional<Aset> asetOpt = repo.findById(this.kodeAset); 

        if (asetOpt.isPresent()) {
            Aset aset = asetOpt.get();
            
            // 2. Isi Label Informasi Aset (Gunakan formatRupiah dan formatTanggal)
            lblIsianKodeAset.setText(aset.getKodeAset());
            lblIsianNamaAset.setText(aset.getNamaAset());
            lblIisianKategori.setText(aset.getKategori());
            // GUNAKAN METODE BARU DI KELAS ASET UNTUK TANGGAL
            lblIsianTanggalPeolehan.setText(Aset.formatTanggal(aset.getTanggalPerolehan())); 
            lblIsianHargaAwal.setText(Aset.formatRupiah(aset.getHargaAwal())); 
            lblIsianLokasiSaatIni.setText(aset.getLokasi());
            lblIsianPJ.setText(aset.getPenanggungJawab());
            

            setTitle("Detail Aset & Riwayat Nilai - " + aset.getKodeAset());
            
            // 3. Isi Tabel Riwayat
            DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
            model.setRowCount(0); // Kosongkan tabel
            
            if (aset.getRiwayatPenyusutan() != null) {
                for (RiwayatPenyusutan riwayat : aset.getRiwayatPenyusutan()) {
                    model.addRow(new Object[]{
                        // GUNAKAN METODE BARU DI KELAS ASET UNTUK TANGGAL
                        Aset.formatTanggal(riwayat.getTanggalHitung()),
                        riwayat.getMetode(),
                        Aset.formatRupiah(riwayat.getNilaiTurun()),
                        Aset.formatRupiah(riwayat.getNilaiSisa())
                    });
                }
            }
        } else {
            System.out.println("Aset dengan kode " + this.kodeAset + " tidak ditemukan.");
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error saat memuat data aset", e);
        JOptionPane.showMessageDialog(this, "Gagal memuat detail aset: " + e.getMessage(), "Error Data", JOptionPane.ERROR_MESSAGE);
    }

}
    
    // ... (rest of initComponents() and main method)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneHistory = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        pnlInfoAset = new javax.swing.JPanel();
        lblKodeAset = new javax.swing.JLabel();
        lblIsianKodeAset = new javax.swing.JLabel();
        lblNamaAset = new javax.swing.JLabel();
        lblIsianNamaAset = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblIisianKategori = new javax.swing.JLabel();
        lblTanggalPerolehan = new javax.swing.JLabel();
        lblIsianTanggalPeolehan = new javax.swing.JLabel();
        lblHargaAwal = new javax.swing.JLabel();
        lblIsianHargaAwal = new javax.swing.JLabel();
        lblLokasiSaatIni = new javax.swing.JLabel();
        lblIsianLokasiSaatIni = new javax.swing.JLabel();
        lblPJ = new javax.swing.JLabel();
        lblIsianPJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Aset & Riwayat Nilai");

        jScrollPaneHistory.setToolTipText("Histori Perubahan Nilai (Penyusutan)");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanngal_Hitung", "Metode", "Turun_Nilai", "Nilai_Sisa"
            }
        ));
        jScrollPaneHistory.setViewportView(tblHistory);

        getContentPane().add(jScrollPaneHistory, java.awt.BorderLayout.CENTER);

        pnlInfoAset.setToolTipText("Informasi Aset");
        pnlInfoAset.setLayout(new java.awt.GridLayout(8, 2, 5, 5));

        lblKodeAset.setText("Kode Aset:");
        pnlInfoAset.add(lblKodeAset);

        lblIsianKodeAset.setText("jLabel4");
        pnlInfoAset.add(lblIsianKodeAset);

        lblNamaAset.setText("Nama Aset:");
        pnlInfoAset.add(lblNamaAset);

        lblIsianNamaAset.setText("jLabel2");
        pnlInfoAset.add(lblIsianNamaAset);

        lblKategori.setText("Kategori:");
        pnlInfoAset.add(lblKategori);

        lblIisianKategori.setText("jLabel11");
        pnlInfoAset.add(lblIisianKategori);

        lblTanggalPerolehan.setText("Tanggal Perolehan:");
        pnlInfoAset.add(lblTanggalPerolehan);

        lblIsianTanggalPeolehan.setText("jLabel6");
        pnlInfoAset.add(lblIsianTanggalPeolehan);

        lblHargaAwal.setText("Harga Awal:");
        pnlInfoAset.add(lblHargaAwal);

        lblIsianHargaAwal.setText("jLabel12");
        pnlInfoAset.add(lblIsianHargaAwal);

        lblLokasiSaatIni.setText("Lokasi Saat Ini:");
        pnlInfoAset.add(lblLokasiSaatIni);

        lblIsianLokasiSaatIni.setText("jLabel14");
        pnlInfoAset.add(lblIsianLokasiSaatIni);

        lblPJ.setText("Penanggung Jawab");
        pnlInfoAset.add(lblPJ);

        lblIsianPJ.setText("jLabel13");
        pnlInfoAset.add(lblIsianPJ);

        getContentPane().add(pnlInfoAset, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogDetailAset dialog = new DialogDetailAset(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneHistory;
    private javax.swing.JLabel lblHargaAwal;
    private javax.swing.JLabel lblIisianKategori;
    private javax.swing.JLabel lblIsianHargaAwal;
    private javax.swing.JLabel lblIsianKodeAset;
    private javax.swing.JLabel lblIsianLokasiSaatIni;
    private javax.swing.JLabel lblIsianNamaAset;
    private javax.swing.JLabel lblIsianPJ;
    private javax.swing.JLabel lblIsianTanggalPeolehan;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKodeAset;
    private javax.swing.JLabel lblLokasiSaatIni;
    private javax.swing.JLabel lblNamaAset;
    private javax.swing.JLabel lblPJ;
    private javax.swing.JLabel lblTanggalPerolehan;
    private javax.swing.JPanel pnlInfoAset;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables
}

