/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUDbdl;
import javax.swing.JOptionPane;
import java.util.Optional;
/**
 *
 * @author alghi
 */
public class FormDialogEditAset extends javax.swing.JDialog {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormDialogEditAset.class.getName());
    private AsetRepository asetRepository;
    private String kodeAset;
    private Aset asetSaatIni;
    /**
     * Creates new form FormDialogEditAset
     */
    // File: FormDialogEditAset.java

// Constructor yang dipanggil dari FormAset (Ini adalah constructor yang benar)
public FormDialogEditAset(java.awt.Frame parent, boolean modal, AsetRepository repo, String kodeAset) {
        super(parent, modal);
        this.asetRepository = repo; // Menerima AsetRepository
        this.kodeAset = kodeAset;   // Menerima kode aset
        initComponents();
        
        // Memuat data setelah komponen diinisialisasi
        muatDataAsetUntukEdit();
    }
    
    /**
     * 
     */
    public FormDialogEditAset(java.awt.Frame parent, boolean modal) {
        // Panggil constructor utama dengan nilai null
        this(parent, modal, null, null);
    }
    
    private void muatDataAsetUntukEdit() {
        if (asetRepository == null || kodeAset == null) return;
    
    // --- TAMBAHAN: MENGISI MODEL COMBO BOX DENGAN DATA DUMMY/MOCK ---
    // Dalam aplikasi nyata, data ini akan diambil dari database master/referensi
    String[] kategoriList = new String[] { "Elektronik", "Peralatan Kantor", "Perabotan", "Kendaraan" };
    String[] lokasiList = new String[] { "Ruang Server", "Lobby Utama", "Ruang Meeting", "Gudang", "Parkiran" };
    String[] pjList = new String[] { "Afrizal", "Andi", "Budi", "Sinta", "Dewi" };
    String[] kondisiList = new String[] { "Baik", "Perlu Perbaikan", "Rusak", "Sangat Baik" };
    
    cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(kategoriList));
    cbxLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(lokasiList));
    PenanggungJawab.setModel(new javax.swing.DefaultComboBoxModel<>(pjList));

    // ---------------------------------------------------------------------

    try {
        Optional<Aset> asetOpt = asetRepository.findById(kodeAset);
        if (asetOpt.isPresent()) {
            asetSaatIni = asetOpt.get();
            setTitle("Edit Aset: " + kodeAset + " - " + asetSaatIni.getNamaAset());
            
            // Set item yang dipilih berdasarkan data aset
            cbxKategori.setSelectedItem(asetSaatIni.getKategori());
            cbxLokasi.setSelectedItem(asetSaatIni.getLokasi());
            PenanggungJawab.setSelectedItem(asetSaatIni.getPenanggungJawab()); 
        

        } else {
            JOptionPane.showMessageDialog(this, "Aset tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data aset untuk edit", e);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKategori = new javax.swing.JLabel();
        cbxKategori = new javax.swing.JComboBox<>();
        lblLokasi = new javax.swing.JLabel();
        cbxLokasi = new javax.swing.JComboBox<>();
        lblPenanggungJawab = new javax.swing.JLabel();
        PenanggungJawab = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridLayout(5, 3, 10, 10));

        lblKategori.setText("Kategori");
        getContentPane().add(lblKategori);

        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(cbxKategori);

        lblLokasi.setText("Lokasi");
        getContentPane().add(lblLokasi);

        cbxLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLokasiActionPerformed(evt);
            }
        });
        getContentPane().add(cbxLokasi);

        lblPenanggungJawab.setText("Penanggung Jawab");
        getContentPane().add(lblPenanggungJawab);

        PenanggungJawab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PenanggungJawab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenanggungJawabActionPerformed(evt);
            }
        });
        getContentPane().add(PenanggungJawab);
        getContentPane().add(jLabel6);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (asetSaatIni == null) return;

        try {
            String kategoriBaru = cbxKategori.getSelectedItem().toString();
            String lokasiBaru = cbxLokasi.getSelectedItem().toString();
            String pjBaru = PenanggungJawab.getSelectedItem().toString();
          
            
            // 2. Update objek Aset
            asetSaatIni.setKategori(kategoriBaru);
            asetSaatIni.setLokasi(lokasiBaru);
            asetSaatIni.setPenanggungJawab(pjBaru);
          
            
            // 3. Simpan (UPDATE)
            asetRepository.save(asetSaatIni); 
            
            JOptionPane.showMessageDialog(this, "Perubahan aset berhasil disimpan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal menyimpan perubahan aset", e);
            JOptionPane.showMessageDialog(this, "Gagal menyimpan perubahan: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKategoriActionPerformed

    private void cbxLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLokasiActionPerformed

    private void PenanggungJawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenanggungJawabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenanggungJawabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormDialogEditAset dialog = new FormDialogEditAset(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PenanggungJawab;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxKategori;
    private javax.swing.JComboBox<String> cbxLokasi;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblPenanggungJawab;
    // End of variables declaration//GEN-END:variables
}
