/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CRUDbdl;

import javax.swing.SwingUtilities;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Login.ConnectDatabaseLoginBDL;
import java.sql.*;

/**
 *
 * @author afrizal
 */
public class FormAset extends javax.swing.JPanel {

    /**
     * Creates new form FormAset
     */
    public FormAset() {
        initComponents();
        muatDataAsetKeTabel();
    }

    private void muatDataAsetKeTabel() {
        DefaultTableModel model = (DefaultTableModel) tblAset.getModel();
        model.setRowCount(0);

        try {
            Connection conn = ConnectDatabaseLoginBDL.getConnection();

            // Use JOIN to get names instead of IDs
            String sql = "SELECT a.kode_aset_unik, a.nama_aset, k.nama_kategori, "
             + "l.nama_lokasi, p.nama_pegawai, a.nilai_buku "
             + "FROM aset a "
             + "LEFT JOIN kategori k ON a.id_kategori = k.id_kategori "
             + "LEFT JOIN lokasi l ON a.id_lokasi = l.id_lokasi "
             + "LEFT JOIN pegawai p ON a.id_pegawai = p.id_pegawai "
             + "ORDER BY a.kode_aset_unik ASC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                // Format Rupiah
                double nilai = rs.getDouble("nilai_buku");
                java.text.NumberFormat cur = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
                String nilaiFormatted = cur.format(nilai);

                model.addRow(new Object[]{
                    rs.getString("kode_aset_unik"),
                    rs.getString("nama_aset"),
                    rs.getString("nama_kategori"), // Shows "Elektronik" instead of "KAT-01"
                    rs.getString("nama_lokasi"), // Shows "Gudang" instead of "LOK-01"
                    rs.getString("nama_pegawai"), // Shows "Budi" instead of "101"
                    nilaiFormatted
                });
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load aset: " + e.getMessage());
        }
    }

    private String getKodeAsetDipilih() {
        int barisDipilih = tblAset.getSelectedRow();
        if (barisDipilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih satu baris aset dari tabel.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return tblAset.getValueAt(barisDipilih, 0).toString();
    }

    private Frame getParentFrame() {
        // Mencari Window teratas yang berisi komponen ini (JPanel) dan mengembalikannya sebagai Frame.
        return (Frame) SwingUtilities.getWindowAncestor(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnDetailRiwayat = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapusAset = new javax.swing.JButton();
        btnProsesPenyusutan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAset = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("🔄 Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);

        btnDetailRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        btnDetailRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        btnDetailRiwayat.setText("📄 Detail & Riwayat");
        btnDetailRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailRiwayatActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetailRiwayat);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("✏️ Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        btnHapusAset.setBackground(new java.awt.Color(255, 255, 255));
        btnHapusAset.setForeground(new java.awt.Color(0, 0, 0));
        btnHapusAset.setText(" 🗑️ Hapus Aset");
        btnHapusAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAsetActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapusAset);

        btnProsesPenyusutan.setBackground(new java.awt.Color(255, 255, 255));
        btnProsesPenyusutan.setForeground(new java.awt.Color(0, 0, 0));
        btnProsesPenyusutan.setText(" 📉 Proses Penyusutan");
        btnProsesPenyusutan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesPenyusutanActionPerformed(evt);
            }
        });
        jPanel1.add(btnProsesPenyusutan);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tblAset.setBackground(new java.awt.Color(255, 255, 255));
        tblAset.setForeground(new java.awt.Color(0, 0, 0));
        tblAset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Aset", "Nama Aset", "Kategori", "Lokasi", "Penanggung Jawab", "Nilai Buku"
            }
        ));
        tblAset.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblAset.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblAset);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String kodeAset = getKodeAsetDipilih();
        if (kodeAset == null) {
            return;
        }

        Frame parentFrame = getParentFrame();

        // 3. Create and Show the Dialog
        // We pass 'null' for the repository because FormDialogEditAset handles its own DB connection now.
        FormDialogEditAset formEdit = new FormDialogEditAset(parentFrame, true, null, kodeAset);

        formEdit.setLocationRelativeTo(this); // Center it
        formEdit.setVisible(true);

        muatDataAsetKeTabel();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        muatDataAsetKeTabel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDetailRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailRiwayatActionPerformed
        // TODO add your handling code here:
        String kodeAset = getKodeAsetDipilih();
        if (kodeAset == null) {
            return;
        }

        java.awt.Frame owner = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Pass 'null' for the repository argument
        DialogDetailAset dialog = new DialogDetailAset(owner, true, null, kodeAset);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnDetailRiwayatActionPerformed

    private void btnHapusAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAsetActionPerformed
        // TODO add your handling code here:
        String kodeAset = getKodeAsetDipilih();
        if (kodeAset == null) {
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(null,
         "Apakah Anda yakin ingin menghapus aset dengan kode: " + kodeAset + "?\n"
         + "Tindakan ini tidak dapat dibatalkan.",
         "Konfirmasi Hapus",
         javax.swing.JOptionPane.YES_NO_OPTION,
         javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            Connection conn = null;
            try {
                conn = ConnectDatabaseLoginBDL.getConnection();

                // 3. Execute Delete Query
                String sql = "DELETE FROM aset WHERE kode_aset_unik = ?";
                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, kodeAset);

                int rowsAffected = ps.executeUpdate();

                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Aset berhasil dihapus!");
                    muatDataAsetKeTabel(); // Refresh the table
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Gagal: Aset tidak ditemukan di database.");
                }

            } catch (java.sql.SQLException e) {
                // 4. Handle Foreign Key Constraints (SQLState 23xxx)
                // This happens if the asset is used in Maintenance or Depreciation tables
                if (e.getSQLState() != null && e.getSQLState().startsWith("23")) {
                    javax.swing.JOptionPane.showMessageDialog(null,
                     "Gagal Menghapus:\nAset ini memiliki data terkait (Riwayat Pemeliharaan/Penyusutan).\n"
                     + "Hapus data terkait terlebih dahulu jika ingin menghapus aset ini.",
                     "Data Terproteksi",
                     javax.swing.JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Error Database: " + e.getMessage());
                }
            } catch (Exception e) {
                System.out.println("Error Hapus: " + e);
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }
                } catch (Exception ex) {
                }
            }
        }
    }//GEN-LAST:event_btnHapusAsetActionPerformed

    private void btnProsesPenyusutanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesPenyusutanActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
         "Apakah Anda yakin ingin memproses penyusutan untuk periode ini?\n"
         + "Proses ini akan mengurangi Nilai Buku aset berdasarkan Umur Ekonomisnya.",
         "Konfirmasi Penyusutan", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        java.sql.Connection conn = null;
        try {
            conn = Login.ConnectDatabaseLoginBDL.getConnection();
            conn.setAutoCommit(false);

            String sqlGet = "SELECT a.kode_aset_unik, a.harga_perolehan, a.nilai_buku, k.umur_ekonomis_tahun "
             + "FROM aset a "
             + "JOIN kategori k ON a.id_kategori = k.id_kategori "
             + "WHERE a.nilai_buku > 0 AND k.umur_ekonomis_tahun > 0";

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sqlGet);

            String sqlUpdateAset = "UPDATE aset SET nilai_buku = ? WHERE kode_aset_unik = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdateAset);

            String sqlInsertHistory = "INSERT INTO penyusutan (kode_aset_unik, tanggal_hitung, metode, nilai_penyusutan, nilai_buku_akhir) VALUES (?, CURRENT_DATE, ?, ?, ?)";
            PreparedStatement psInsert = conn.prepareStatement(sqlInsertHistory);

            int countProcessed = 0;

            while (rs.next()) {
                String kode = rs.getString("kode_aset_unik");
                double hargaBeli = rs.getDouble("harga_perolehan");
                double nilaiBukuLama = rs.getDouble("nilai_buku");
                int umurTahun = rs.getInt("umur_ekonomis_tahun");

                double penyusutanPerBulan = hargaBeli / (umurTahun * 12);

                // Calculate New Value
                double nilaiBukuBaru = nilaiBukuLama - penyusutanPerBulan;
                double nilaiPenyusutanNyata = penyusutanPerBulan;

                // Handle logic if asset value drops below 0
                if (nilaiBukuBaru < 0) {
                    nilaiBukuBaru = 0;
                    nilaiPenyusutanNyata = nilaiBukuLama;
                }

                psUpdate.setDouble(1, nilaiBukuBaru);
                psUpdate.setString(2, kode);
                psUpdate.addBatch();

                psInsert.setString(1, kode);
                psInsert.setString(2, "Garis Lurus");
                psInsert.setDouble(3, nilaiPenyusutanNyata);
                psInsert.setDouble(4, nilaiBukuBaru);
                psInsert.addBatch();

                countProcessed++;
            }

            psUpdate.executeBatch();
            psInsert.executeBatch();

            conn.commit();
            javax.swing.JOptionPane.showMessageDialog(this,
             "Penyusutan Selesai!\n" + countProcessed + " aset telah disusutkan nilainya.");

            muatDataAsetKeTabel();

        } catch (Exception e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (Exception ex) {
            }
            System.out.println("Error Penyusutan: " + e);
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Proses: " + e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception ex) {
            }
        }

    }//GEN-LAST:event_btnProsesPenyusutanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailRiwayat;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapusAset;
    private javax.swing.JButton btnProsesPenyusutan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAset;
    // End of variables declaration//GEN-END:variables
}
