/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CRUDbdl;
import javax.swing.JOptionPane;
import java.awt.Frame;
import java.util.Optional;
import java.util.logging.Logger;
/**
 *
 * @author alghi
 */
 

public class FormDialogEditLogistik extends javax.swing.JDialog {
    private static final Logger logger = Logger.getLogger(FormDialogEditLogistik.class.getName());
private LogistikRepository logistikRepository;
    private String idInventaris;
    private Logistik logistikSaatIni;
    
public FormDialogEditLogistik(java.awt.Frame parent, boolean modal, LogistikRepository repo, String idInventaris) {
        super(parent, modal);
        this.logistikRepository = repo;
        this.idInventaris = idInventaris;
        
         initComponents();
        // Memuat data setelah komponen diinisialisasi
        muatDataLogistikUntukEdit();
       
    }
    
    public FormDialogEditLogistik(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }
    
    private void muatDataLogistikUntukEdit() {
      if (logistikRepository == null || idInventaris == null) return;
        
        try {
            // Asumsi LogistikRepository memiliki findById(String id)
            Optional<Logistik> logistikOpt = logistikRepository.findById(idInventaris);
            
            if (logistikOpt.isPresent()) {
                logistikSaatIni = logistikOpt.get();
                setTitle("Edit Logistik: " + logistikSaatIni.getNamaBarang());
                
                // Mengisi label informasi yang tidak bisa diubah
                lblIdInventaris.setText(logistikSaatIni.getIdInventaris());
                lblNamaBarang.setText(logistikSaatIni.getNamaBarang());
                
                // Mengisi field input yang dapat diubah
                txtSatuan.setText(logistikSaatIni.getSatuan());
                txtStokMinimum.setText(String.valueOf(logistikSaatIni.getStokMinimum()));

            } else {
                JOptionPane.showMessageDialog(this, "Item logistik tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data logistik: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAksi = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        pnlInput = new javax.swing.JPanel();
        IDInventaris = new javax.swing.JLabel();
        lblIdInventaris = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        SatuanBaru = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        StokMinimum = new javax.swing.JLabel();
        txtStokMinimum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Satuan dan Stok Minimum Logistik");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);

        pnlAksi.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        pnlAksi.add(btnBatal);

        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        pnlAksi.add(btnSimpan);

        getContentPane().add(pnlAksi, java.awt.BorderLayout.SOUTH);

        pnlInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInput.setToolTipText("pnlInput");
        pnlInput.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        IDInventaris.setText("ID Inventaris:");
        pnlInput.add(IDInventaris);

        lblIdInventaris.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdInventaris.setText("jLabel5");
        pnlInput.add(lblIdInventaris);

        NamaBarang.setText("Nama Barang:");
        pnlInput.add(NamaBarang);

        lblNamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamaBarang.setText("jLabel3");
        pnlInput.add(lblNamaBarang);

        SatuanBaru.setText("Satuan Baru:");
        pnlInput.add(SatuanBaru);

        txtSatuan.setText("jTextField1");
        txtSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatuanActionPerformed(evt);
            }
        });
        pnlInput.add(txtSatuan);

        StokMinimum.setText("Stok Minimum Baru:");
        pnlInput.add(StokMinimum);

        txtStokMinimum.setText("jTextField2");
        txtStokMinimum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokMinimumActionPerformed(evt);
            }
        });
        pnlInput.add(txtStokMinimum);

        getContentPane().add(pnlInput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (logistikSaatIni == null) return;
        
        try {
            String satuanBaru = txtSatuan.getText().trim();
            int stokMinimumBaru = Integer.parseInt(txtStokMinimum.getText().trim());
            
            if (satuanBaru.isEmpty() || stokMinimumBaru < 0) {
                 JOptionPane.showMessageDialog(this, "Satuan tidak boleh kosong dan Stok Minimum harus >= 0.", "Validasi Input", JOptionPane.WARNING_MESSAGE);
                 return;
            }

            // 1. Update objek Logistik
            logistikSaatIni.setSatuan(satuanBaru);
            logistikSaatIni.setStokMinimum(stokMinimumBaru);
            
            // 2. Simpan (UPDATE) melalui Repository
            logistikRepository.save(logistikSaatIni); 
            
            JOptionPane.showMessageDialog(this, "Perubahan Satuan dan Stok Minimum berhasil disimpan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input Stok Minimum harus berupa angka yang valid.", "Validasi Input", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan perubahan: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtStokMinimumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokMinimumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokMinimumActionPerformed

    private void txtSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormDialogEditLogistik dialog = new FormDialogEditLogistik(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDInventaris;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JLabel SatuanBaru;
    private javax.swing.JLabel StokMinimum;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel lblIdInventaris;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JPanel pnlAksi;
    private javax.swing.JPanel pnlInput;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtStokMinimum;
    // End of variables declaration//GEN-END:variables
}
